# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-07-18 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodactive',
            options={'verbose_name': '美食活动详情', 'verbose_name_plural': '美食活动详情'},
        ),
        migrations.AddField(
            model_name='active',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='ac/', verbose_name='活动图片'),
        ),
        migrations.AddField(
            model_name='voteactive',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='ac/', verbose_name='活动图片'),
        ),
    ]
