# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-07-18 12:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('flapp', '0003_auto_20190718_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='active',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='活动结束时间'),
        ),
        migrations.AlterField(
            model_name='active',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='活动开始时间'),
        ),
    ]
