# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-07-18 12:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('flapp', '0004_auto_20190718_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='voteactive',
            name='is_status',
            field=models.BooleanField(default=False, verbose_name='是否置顶'),
        ),
        migrations.AddField(
            model_name='voteactive',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='开始时间'),
        ),
        migrations.AlterField(
            model_name='voteactive',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='结束时间'),
        ),
    ]
