# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-07-18 13:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flapp', '0006_information_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsor',
            name='active_num',
        ),
    ]
