# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-07-18 14:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flapp', '0007_remove_sponsor_active_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeActive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='类型')),
            ],
            options={
                'verbose_name': '报名活动类型',
                'verbose_name_plural': '报名活动类型',
            },
        ),
        migrations.CreateModel(
            name='Votetype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='类型')),
            ],
            options={
                'verbose_name': '投票活动类型',
                'verbose_name_plural': '投票活动类型',
            },
        ),
        migrations.AddField(
            model_name='active',
            name='typeactive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flapp.TypeActive', verbose_name='活动类型'),
        ),
        migrations.AddField(
            model_name='voteactive',
            name='votetype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flapp.Votetype', verbose_name='活动类型'),
        ),
    ]
