# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-07-20 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flapp', '0010_auto_20190720_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergood',
            name='vote_num',
            field=models.IntegerField(default=0, verbose_name='参与投票次数'),
        ),
    ]
