# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-07-22 16:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flapp', '0011_usergood_vote_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='information',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='voteactive',
            old_name='title',
            new_name='name',
        ),
    ]
