# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-07-23 10:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flapp', '0012_auto_20190722_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='userenroll',
            name='parea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parea', to='flapp.Area', verbose_name='法人所属区域'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='active',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flapp.Active', verbose_name='活动'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flapp.User', verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='userenroll',
            name='phone',
            field=models.CharField(max_length=11, unique=True, verbose_name='手机号'),
        ),
    ]
